# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 113b92ce6a58ce34959fbfd943d9f22ca3b78cb83ab5ff0cb3bede49c5df7a76ddaa2f32ef385529c2abac38d96c81f2022412986686ce6d60b7ff67aaae6296

test:
  secret_key_base: 4be49cf83e5c66133b8948549f6bddac3f021e029011567be272583b3cf6763075285ad96b9a46f148fbd216dd3091856598d4ae4227cc3664b5130d0732eba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
